import Head from 'next/head';
import { Container, Switch } from '@maxst-designsystem/maxst-design-system';
import ButtonGroups from '@/components/ButtonGroup';
import BodyHeader from '@/components/BodyHeader';
import {
  Breadcrumb,
  Title,
  Text,
} from '@maxst-designsystem/maxst-design-system';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title type="title" size="xl" role={1}>
          Maxst design system Test
        </Title>
        <Container>
          <BodyHeader />
          <br />
          <ButtonGroups />
        </Container>
      </main>
    </>
  );
}
