import Head from 'next/head';
import { Container, Switch } from '@maxst-designsystem/maxst-design-system';
import ButtonGroups from '@/components/ButtonGroup';
import { Main } from '@/layout/main/MainStyle';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <br />
          <ButtonGroups />
        </Container>
      </Main>
    </>
  );
}
