import Head from 'next/head';
import ButtonGroups from '@/components/ButtonGroup';
import { Main } from '@/layout/main/MainStyle';
import { ContentRight } from '@components/content';
import { MyContainer } from '@layout/container/ContainerStyle';
import Sidebar from '@components/sidebar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyContainer>
        <Sidebar selectedId="vps-tracker" />
        {/* <ButtonGroups /> */}
        <ContentRight />
      </MyContainer>
    </>
  );
}
